### ISSUE TITLE
bufr/11.6.0 doesn't work for sndp codes while 11.5.0 works fine

### ISSUE THREAD

**Issue by JunDu-NOAA** [NOAA-EMC/NCEPLIBS-grib_util#136]
bufr/11.6.0 on WCOSS2 doesn't work for bufr sndp codes
 of both arw and nmmb models.  Here is the error I got after I tested
 sref_arw_sndp
 and sref_nmb_sndp jobs:

 581.863 + /lfs/h2/emc/lam/noscrub/Jun.Du/sref.v7_cray/exec/sref_arw_sndp
581.863 + 0< modtop.parm 1> sndp.out
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
sref_arw_sndp      0000000000449C9A  Unknown               Unknown  Unknown
libpthread-2.26.s  000014630D4832D0  Unknown               Unknown  Unknown
sref_arw_sndp      000000000040A2B0  status_                    76  status.f
sref_arw_sndp      0000000000403446  Unknown               Unknown  Unknown
sref_arw_sndp      00000000004062A8  Unknown               Unknown  Unknown
sref_arw_sndp      0000000000402DD2  Unknown               Unknown  Unknown
[libc-2.26.so](http://libc-2.26.so/)       000014630D0D934A  __libc_start_main     Unknown  Unknown
sref_arw_sndp      0000000000402CEA  Unknown               Unknown  Unknown
[nid001085.dogwood.wcoss2.ncep.noaa.gov](http://nid001085.dogwood.wcoss2.ncep.noaa.gov/): rank 0 exited with code 174

However, I found that they work ok if I compile the codes with bufr/11.5.0.  BTW, the executables is much larger in size with 11.6.0
version than the 11.5.0 version. 

Although it doesn't work for sref sndp for now, I guess it might also not work for other models like 
nam, rap etc.  since currently rap uses bufr/11.4.0 and nam uses bufr/11.5.0 (I talked to 
Eric, Ben and Geoff about this).

**Comment by edwardhartnett** [comment]
Should this be in the NCEPLIBS-bufr project?

**Comment by edwardhartnett** [comment]
@jbathegit do you have any guidance to offer here?

**Comment by jbathegit** [comment]
This is the first I've heard about this, and this issue is now more than 18 months old, so do we even know if this is still a problem at this point?

Unfortunately the above output doesn't really tell me much about where exactly there may have been a problem.  Please note that Release Notes for all of the different library versions are available at https://noaa-emc.github.io/NCEPLIBS-bufr/md__home_runner_work_NCEPLIBS_bufr_NCEPLIBS_bufr_bufr_docs_ReleaseNotes.html, so maybe something in there might be relevant?  For example, is the application in question pointing to a _DA library build which no longer exists beginning with v11.6.0?

**Comment by edwardhartnett** [comment]
@JunDu-NOAA is this still and issue?

**Comment by JunDu-NOAA** [comment]
This is a very old issue during the WCOSS2 transition. It should be ok now
and you can close it.  -- Jun
